### ISSUE TITLE
[monitoring] Add X-OW-EXTRA-LOGGING: on

### ISSUE THREAD

**Issue by rofe** [adobe/helix-ops#63]
If we decide we do https://github.com/adobe/helix-publish/issues/403, we will need this.

**Comment by tripodsan** [comment]
or send the X-Debug header

**Comment by rofe** [comment]
> or send the X-Debug header

Ah ok, we already do that. Closing 😄

**Comment by rofe** [comment]
Wait, if https://github.com/adobe/helix-publish/issues/403 isn't implemented, there wouldn't anything to retrieve for successful activations, even with `X-Debug` header, would it?

**Comment by rofe** [comment]
As @trieloff suggested in https://github.com/adobe/helix-publish/issues/403#issuecomment-627167529, we should add the `X-OW-EXTRA-LOGGING` header in the monitor request so we can continue to extract the activation records.
