### ISSUE TITLE
Use Major action versions for monitoring scripts

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-ops#67]
## Overview
the current monitoring scripts test the minor versions of the deployed actions,

eg: `dispatch@v3.2`

Helix internally always uses the major version. so we are testing something that is not actually used.

The following problem can arise:

- assume `dispatcher@v3.2.1` is the latest version
- `v3` -> `v3.2.1`
- `v3.2` -> `v3.2.1`

now, we release the next minor version:

- `v3` -> `v3.3.0`
- `v3.3` -> `v3.3.0`
- `v3.2` -> `v3.2.1`

the monitoring scripts get automatically updated during the release and now test `@v3.3`.

Assume, that the new version causes problems, and we need to immediately switch the `v3` link back to `v3.2.1`. without updating the monitoring scripts, they will continue to test `v3.3` (hence `v3.3.0`) and keep reporting errors.

## Proposed Actions
Use the major version only for monitoring scripts.

**Comment by tripodsan** [comment]
@trieloff @rofe WDYT?

**Comment by trieloff** [comment]
Agree.

**Comment by rofe** [comment]
Released in CircleCI orb adobe/helix-post-deploy@1.7.0
