### ISSUE TITLE
Enable semantic release bot on this repo

### ISSUE THREAD

**Issue by rofe** [adobe/helix-ops#73]
@trieloff can you help?

**Comment by rofe** [comment]
The workflow config is [there](https://github.com/adobe/helix-ops/blob/master/.github/workflows/semver-check.yaml), but that alone doesn't seem to do the trick...

**Comment by trieloff** [comment]
No, that should be all that's needed.

**Comment by trieloff** [comment]
https://github.com/adobe/helix-ops/pull/69#issuecomment-619939673 is a comment left by the bot.

**Comment by rofe** [comment]
Ah, cool! I didn't see one on [this PR](https://github.com/adobe/helix-ops/pull/72) though...is there a minimum time to wait between creating and merging a PR (it was 7h in this case)?
